controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lite6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

lite6_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
